application: pure-data
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:


- url: /cron/scrape
  script: main.app
  login: admin

- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg))
  static_files: \1
  upload: images/(.*\.(gif|png|jpg))

- url: /favicon.ico
  static_files: images/favicon.ico
  upload:       images/favicon.ico

- url: /(.*\.(js))
  static_files: \1
  upload: js/(.*\.(js))


- url: .*
  script: main.app



libraries:
 - name: jinja2
   version: latest

builtins:
- remote_api: on